apiVersion: v1
kind: Secret
metadata:
    name: testsecret
type: Opaque
data:
    username: ENC[AES256_GCM,data:jhHib64DRCKYc3zL/Nas8MN1X8I=,iv:jgmMEYV76eXxkcc3XrJxJAZ+qPcc2gs2Khb1pfCawiM=,tag:KOO+wJfKzxRsNwUeSD+9hw==,type:str]
    password: ENC[AES256_GCM,data:Ob+/xsTVaHrhVz45jjcwMaaHLOA=,iv:WrurI9V91Chw+UUfSf+HrVOAFj3EZNN/54oJD+4f8gU=,tag:BXcxIRsDjhhzzu+eGudvWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nvjwnwetrzd4xkv6ylks44hm6pfz6dtnsfzay5n3azmapwrz48qy48swx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4cXpkOVVTSDRXdUVIK05S
            NXlXUk1pZmQ3RlJINy8vT1V6MkZVcEhTcVY4ClhoUVY1bW5VL3M5ZndvYUhWaFNt
            SjJ6N2J6NXBOWlpRdENrNFd4RVMvOGMKLS0tIGlveWZmVitkTWVqMkl5Z2hHN0tk
            MDJDVXpUSVhSYnhTMTYyK0o5NUtZK0kKVdwdZ3CUVAAKTsnqBcMYDGtYuHy7EfrO
            ntlkNJFzNOyzwemDQSdfEc35jDUoaVlNF6rUjt0xoFw7kHneDEBxHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-15T14:57:48Z"
    mac: ENC[AES256_GCM,data:bS/MB6UAKu5r9t4Et5ekW+3wkzJUu1SIb5QTmbWNuSkk44gnfhFplEGlT4f0X1bgCL1COFt2DsEMYvP0/5OX6dMVMNbGrN1u+oD9fzsI8vPHZw3a7O9lzE2P6pvKBY2Mlurgo8nWdD1G/WE7WU0XVjhcfUioHQKPlobsiY/NVCA=,iv:K9EqIrLnUCEcGC6MNb4AF0QCst2zM4vilBGkYzf4pA4=,tag:lwJPGwIWxKescpEk76taTw==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.7.3
